### ISSUE TITLE
iSensor-FX-API Error: timeout occurred while canceling a stream. Cancel USB ReqCode: 0x00C0 

### ISSUE THREAD

**Issue by jinbm2kdw** [analogdevicesinc/iSensor-FX3-API#11]
Dear @juchong and @ajn96

I'm a chief research engineer of Daewoo E & C. Co. Ltd, Korea. 

I can not acquire sensor data of ADIS16480 IMU with EVAL-ADIS-FX3 Eval Board in Matlab. (3 Windows 10 systems with Matlab 2020b, 2 ADIS16480 IMU + 2 EVAL-AIDS-FX3)

There are no problems to acquire data by the iSensor FX3 Eval program as shown in the below figure. 

<img width="556" alt="iSensor FX3 Eval-no error" src="https://user-images.githubusercontent.com/50645979/119443301-5a0b4780-bd64-11eb-81df-55af6e80b845.png">

But I can not acquire data with the example Matlab file in github.com/analogdeviceinc/iSensor-FX3-API

Two types of errors I have encountered as shown in the below figures.

One is a timeout error in line 30 of Matlab file in case of the presence of the iSensor FX3 Eval Program.
(ERROR: Timeout occurred while canceling a stream. Cancel USB ReqCode: 0x00C0)

The other is also a timeout error in line 70 of Matlab file in case of the absence of the iSensor FX3 Eval Program.

<img width="1280" alt="iSensor FX3 API error1" src="https://user-images.githubusercontent.com/50645979/119443306-5d9ece80-bd64-11eb-87e1-d37512bef99a.png">

<img width="1280" alt="iSensor FX3 API error2" src="https://user-images.githubusercontent.com/50645979/119443308-60012880-bd64-11eb-93ea-6d7f47480745.png">

If this problem can not be resolved, should I purchase the Total Phase Aardvark I2C/SPI Interface or the NI-845x I2C/SPI Interface with Matlab?

Thank you.

**Comment by ajn96** [comment]
Hi @jinbm2kdw,

Thank you for your interest in the EVAL-ADIS-FX3 and ADIS16480. 

The error code you are seeing occurs when the FX3 board times out sending data back up to the PC. This can happen when data ready triggering for SPI transactions is enabled, and no data ready edges are detected. This can have a couple common causes:
1. Data ready is not configured correctly on the DUT
2. Data ready is not toggling (for example, if the IMU is placed in external sync mode without a sync clock)
3. There is a hardware issue (open or short) preventing the data ready signal from reaching the eval board

Since everything is working in the GUI, my guess is that there is a mismatch between the EVAL-ADIS-FX3 data ready configuration and the DUT configuration. The data ready pin assignment can be changed on both ends.

I took the liberty of making a ADIS1648x matlab example which explicitly configures the DUT and EVAL-ADIS-FX3 to have matching settings. 
See: https://github.com/analogdevicesinc/iSensor-FX3-API/blob/master/src_wrapper/examples/Matlab/adis16488_example.m

Running this script produces the expected results. Accel channel FFT:
![data_plot_adis16487](https://user-images.githubusercontent.com/35480179/119547763-7eb2ef80-bd63-11eb-8398-cb046d55c556.PNG)

Console output (read of product ID and measurement of data ready freq):
![console_output_adis16487](https://user-images.githubusercontent.com/35480179/119547804-8c687500-bd63-11eb-8f4a-d63cb002fd2c.PNG)

If you are curious what other functions the wrapper provides, the full class documentation can be found here:
https://analogdevicesinc.github.io/iSensor-FX3-API/api/html/40759f04-37a2-d0a6-dda1-24c2439ded89.htm

Let me know if the modified matlab script resolves your issue.

Thanks,

Alex Nolan

**Comment by jinbm2kdw** [comment]
The ADIS1648x Matlab example you posted works fine. I really appreciate you.

<img width="1280" alt="iSensor FX3 API error1" src="https://user-images.githubusercontent.com/50645979/119583197-06027080-be01-11eb-98b8-75356b625074.png">
<img width="421" alt="FFT plot success" src="https://user-images.githubusercontent.com/50645979/119583213-0e5aab80-be01-11eb-8985-f2a169bb3eae.png">
